export KEYTIMEOUT=1
export GOROOT=/usr/local/opt/go/libexec
export GOPATH=$HOME/.go
export PATH=$HOME/bin:/usr/local/opt/openssl/bin:/usr/local/opt/python/libexec/bin:/usr/local/bin:/usr/local/sbin:/usr/local/share/npm/bin:$GOROOT/bin:$GOPATH/bin:$HOME/.cargo/bin:$HOME/.local/bin:$PATH
export EDITOR='vim -p'
export VISUAL='vim -p'
export JAVA_HOME=$(/usr/libexec/java_home)
export NODE_PATH=/usr/local/lib/node_modules
export GPG_TTY=$(tty)
